/// A person generated by the randomuser.me API: name, email, photo, phone
/// and location. Used to back new common-user accounts — once assigned to
/// an account at sign-up, it becomes that account's permanent profile.
class ExternalProfile {
  const ExternalProfile({
    required this.firstName,
    required this.lastName,
    required this.email,
    required this.avatarUrl,
    required this.phone,
    required this.city,
    required this.country,
  });

  final String firstName;
  final String lastName;
  final String email;
  final String avatarUrl;
  final String phone;
  final String city;
  final String country;

  String get fullName => '$firstName $lastName';

  factory ExternalProfile.fromRandomUserJson(Map<String, dynamic> json) {
    final name = json['name'] as Map<String, dynamic>;
    final picture = json['picture'] as Map<String, dynamic>;
    final location = json['location'] as Map<String, dynamic>;

    return ExternalProfile(
      firstName: name['first'] as String,
      lastName: name['last'] as String,
      email: json['email'] as String,
      avatarUrl: picture['large'] as String,
      phone: json['phone'] as String,
      city: location['city'] as String,
      country: location['country'] as String,
    );
  }
}
